### ISSUE TITLE
[bug] Back buttons throughout the wallet app do nothing

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#100]
**How to reproduce:**

![Screenshot from 2024-10-20 22-40-58](https://github.com/user-attachments/assets/d1523a70-c634-49c6-9dcb-c765e9912d13)
navigate to either import account screen or create account screen and attempt to press the back button. 

This should navigate back to the previous page using the NavController set up in WalletApp.kt

**Comment by trbutler4** [comment]
open the wallet_app directory in android studio and search for TODO(#100) in the codebase to find all places where this needs to be updated.

**Comment by raizo07** [comment]
@trbutler4 can I work on this?

**Comment by sajalbnl** [comment]
@trbutler4 i want to work on this

**Comment by trbutler4** [comment]
@sajalbnl @raizo07 @Mystic-Nayy this issue (and any tagged ODHack9) will be availble when ODHack starts on the 24th. Make sure you go through only dust and are ready to be active during the hack for issues like this

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a kotlin dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by Jethrolopwus** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
A front end developer, proficient with javascript, react and next.js 

### How I plan on tackling this issue
I would create a button and set an navigation back to the previous page and set up navController.

**Comment by trbutler4** [comment]
@raizo07 Hey! Please let me know if you have any questions about the issue, You can ask here or send a message in the telegram group here: https://t.me/+8G3EBNnfyS1lNzYx

**Comment by raizo07** [comment]
@trbutler4  Finishing up, will send in a Pr today
