### ISSUE TITLE
[feat] Transfer funds

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#102]
Add the ability to transfer tokens. 

The logic should be added to the StarknetClient.kt file in wallet_app/
#### References
- [starknet android app example](https://github.com/software-mansion/starknet-jvm/blob/main/androiddemo/src/main/java/com/example/androiddemo/MainActivity.kt)

**Comment by Gerson2102** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to this project!

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### How I plan on tackling this issue
### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello I'm a frontend and a blockchain developer. I will love to work on this issue

**Comment by juandiegocv27** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I’m a software engineer with strong experience in Rust and Cairo, and I’ve recently been working on several blockchain-based projects. I’ve contributed to Starknet-based applications and projects like Starknet Quest and ByteBeasts. Additionally, I have experience integrating Rust with other frameworks, including mobile-based solutions. My experience with both Rust and Cairo, alongside my understanding of Starknet, makes me confident in contributing to this mobile OS project. I’ve worked on secure data handling in previous projects, so working on token transfers would be a natural extension.

### How I plan on tackling this issue
I’d start by taking a close look at the StarknetClient.kt file to see how things are currently set up and understand the flow. After that, I’d check out the Starknet Android app example to get a feel for how token transfers are handled there and how I can adapt that for this project. Once I have a clear picture, I’d add the token transfer functionality in Kotlin, making sure it’s secure and efficient. I’d also make sure to test different scenarios—like invalid addresses, failed transfers, and low balances—so everything works smoothly and reliably.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
My background in blockchain development and mobile app programming positions me well to implement this feature effectively and ensure a smooth user experience during token transfers.

### How I plan on tackling this issue
To add the ability to transfer tokens in the `StarknetClient.kt` file within the `wallet_app/`, I would start by reviewing the StarkNet Android app example for guidance on how token transfers are handled. Then, I would implement the necessary logic for initiating token transfers, which would include:

1. **Creating a Function:** Develop a function within `StarknetClient.kt` to facilitate token transfers, taking parameters like the recipient's address and the amount of tokens to be transferred.

2. **Interacting with the Smart Contract:** Use the appropriate StarkNet functions to call the token contract's transfer method, ensuring compliance with the token standards (like ERC-20 or ERC-721).

3. **Error Handling:** Implement error handling to manage any potential issues during the transfer process, such as insufficient balance or invalid addresses.

4. **User Feedback:** Provide feedback to the user upon successful or failed transfers to enhance the user experience.

5. **Testing:** Finally, I would write unit tests to verify the functionality works as expected.

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello, i'm a frontend and a blockchain developer, pls i would love to work on this issue.

### How I plan on tackling this issue
- I will start by reviewing the Starknet Android app example to understand how token transfers are implemented. 
-I will add a method in the StarknetClient.kt file to handle the token transfer logic.
- i will Create Transaction Payload
-I will use Starknet's SDK to build the transaction and send it to the blockchain.

**Comment by jrmncos** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I'm a Software Enginer SR in web 2.0. Some tickets in this repo are not related exclusive with smart contracts, so my experience can work here. Also I have experience working on mobile. I will apply to various tickets in this repo, so sorry for the spam, I really like the project

### How I plan on tackling this issue
I will add the logic in the file as it is in the description

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a kotlin dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).
**My background and how it can be leveraged**
I am an Android developer with 2 years of experience in Kotlin, Jetpack Compose, and MVVM architecture. I’ve contributed to StarkNet Phone, building wallet and light client apps by integrating APIs and implementing UI/UX features. I'm excited to contribute my skills to this project . ETA - 1 Day

**How I plan on tackling this issue**
I have worked on this earlier also and according to starknet android example will implement transfer funds logic

**Comment by trbutler4** [comment]
@jrmncos Hey! Please let me know if you have any questions about the issue, You can ask here or send a message in the telegram group here: https://t.me/+8G3EBNnfyS1lNzYx
