### ISSUE TITLE
[bug] Account information clipboard icons do nothing

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#103]
**ver:**

**How to reproduce:**

With the wallet app running (wallet_app/), attempt to create a new account and copy account information after it was generated. 

![Screenshot from 2024-10-21 18-40-55](https://github.com/user-attachments/assets/e27cc80d-eba8-4f7d-96e7-ad721201b26c)

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
i am a python dev and willing to contribute

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a cairo dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).
**My background and how it can be leveraged**
I am an Android developer with 2 years of experience in Kotlin, Jetpack Compose, and MVVM architecture. I’ve contributed to StarkNet Phone, building wallet and light client apps by integrating APIs and implementing UI/UX features. I'm excited to contribute my skills to this project . ETA - 1 Day

**Comment by ooochoche** [comment]
I'd like to take this issue.

**Comment by trbutler4** [comment]
@lauchaves Hey! Please let me know if you have any questions about the issue, You can ask here or send a message in the telegram group here: https://t.me/+8G3EBNnfyS1lNzYx

**Comment by lauchaves** [comment]
> @lauchaves Hey! Please let me know if you have any questions about the issue, You can ask here or send a message in the telegram group here: https://t.me/+8G3EBNnfyS1lNzYx

Hey @trbutler4 will do thanks!
