### ISSUE TITLE
[bug] No back button on Add Token screen 

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#104]
**ver:**

**How to reproduce:**

Attempt to add a token, there as no way to go back (except for swiping). Add a back button like the other screens

![Screenshot from 2024-10-21 18-43-45](https://github.com/user-attachments/assets/61702adb-220c-4202-8741-c1525ac221e5)

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello I'm a frontend and a blockchain developer. I will love to work on this issue. Please assign

**Comment by Iwueseiter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
hi

### How I plan on tackling this issue
1. I will observe the design and also the codebase to understand and know where I'm expected to work.
2. I will implement an add screen for confirming pin exactly as what is on the figma and also ensure 
it is highly responsive accross all devices.
3. I will ensure the logic work as expected and also meets the requirements.

ETA: 48 hrs.

**Comment by zleypner** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
to make my first contribution to this project and contribute to the project's success.
I'm also a member of the Dojo Coding community CR.

### How I plan on tackling this issue
First, I’ll read through the Contributor Guidelines and README to ensure I understand the project structure, coding standards, and the process you’re following.

I will add the back button. Then I will tested to make sure it has been fixed.

**Comment by Hoossayn** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a senior Android developer with 5+ years experience building scalable native android apps 

### How I plan on tackling this issue
- check for similar ways back button is added on other screens 
- Add to same button to the AddToken screen

**Comment by MrRoudyk** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Software Engineer with 10 years of experience. For the past 5 years, I’ve specialized in HR Tech solutions, now used by tens of thousands of companies and hundreds of thousands of users. I have also contributed to open source development at OnlyDust ([My OnlyDust Profile](https://app.onlydust.com/u/MrRoudyk)).

I’m passionate about exploring new technologies and currently seeking to deepen my expertise in blockchain, smart contracts, and decentralized applications.

### How I plan on tackling this issue
First, I'll look at how the "Back" buttons work on other screens to understand the logic. Then, I'll add a "Back" button to the "Add Token" screen, set it up to navigate to the previous screen, and test it to make sure it works correctly.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a rust dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by Jethrolopwus** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I'm a front end developer proficient in javascript React, next.js and typescript.

### How I plan on tackling this issue
I will create a dynamic button componet and linked it to the previous page onclicking on it

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

I am an Android developer with 2 years of experience in Kotlin, Jetpack Compose, and MVVM architecture. I’ve contributed to StarkNet Phone, building wallet and light client apps by integrating APIs and implementing UI/UX features. I'm excited to contribute my skills to this project . ETA - 1 Hr

How I plan on tackling this issue
I Will create back button icon and make activity close on click on that icon

**Comment by Iwueseiter** [comment]
Hi @trbutler4 my PR is ready, I’d push it this morning.
