### ISSUE TITLE
[feat] Fetch account token balances

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#107]
Current we are only fetching ETH balance. Add logic to fetch all tokens saved in wallet.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello I'm a frontend and a blockchain developer. I will love to work on this

**Comment by Samuel1-ona** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

My background and how it can be leveraged
Hello, i am a full stack blockchain developer and this is my first issue i am applying on onlydust. I will love to work on the project

**Comment by Oshioke-Salaki** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello i am a frontend developer and cairo developer and i believe i would be able to tackle this issue effectively. I have experience with building web applications and dapps. And i would be gald to take this up.

### How I plan on tackling this issue
I would approach this by studying the codebase to understand the coding styles and technologies used. then i would implement the feature to fetch token balances from the account

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will add logic to fetch all tokens saved in the wallet, expanding our current functionality from just the ETH balance. This involves querying relevant API endpoints to retrieve token balances and updating the UI to display each token's balance alongside the ETH balance. After implementation, I’ll conduct thorough testing to ensure accuracy and functionality, enhancing the overall user experience.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a kotlin dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).
**My background and how it can be leveraged**
I am an Android developer with 2 years of experience in Kotlin, Jetpack Compose, and MVVM architecture. I’ve contributed to StarkNet Phone, building wallet and light client apps by integrating APIs and implementing UI/UX features. I'm excited to contribute my skills to this project . ETA - 1 Day
**How I plan on tackling this issue**
i have worked on this issue earlier also and taking reference from previous will start my work

**Comment by trbutler4** [comment]
@aniruddhaaps sorry for the reassignment the issues i assigned @sajalbnl should all be done together

**Comment by trbutler4** [comment]
this is now correct

**Comment by aniruddhaaps** [comment]
wait i didnt understand, why was i unassigned? :( @trbutler4

**Comment by trbutler4** [comment]
> wait i didnt understand, why was i unassigned? :( @trbutler4

because this issue was best done with the other ones i assigned to @sajalbnl , not your fault, sorry for the confusion
