### ISSUE TITLE
[feat] Add pin confirmation screen 

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#108]
Add screen for confirming PIN

#### References

[design](https://www.figma.com/design/grCm6Jpi2XsQnbAHHE2oCZ/Starknet-Phone-Wallet-App?node-id=83-2&node-type=canvas&t=HmFx3PQAalVmaLqD-0)

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
I would solve this issue to pixel perfect

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer and will love to work on this

**Comment by dahtee** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I'm a frontend and smart contract developer and I'd be happy to contribute to this project as this will
be my first time contributing to this project.

### How I plan on tackling this issue
1. I will observe the design and also the codebase to understand and know where I'm expected to work.
2. I will implement an add screen for confirming pin exactly as what is on the figma and also ensure 
it is highly responsive accross all devices.
3. I will ensure the logic work as expected and also meets the requirements.

ETA: 48 hrs.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
My background in frontend development enables me to create intuitive and secure interfaces, ensuring a seamless user experience during the PIN confirmation process.

### How I plan on tackling this issue
To solve the issue of adding a screen for confirming a PIN, I would first refer to the provided design specifications to ensure the new screen aligns with the overall app aesthetic and user experience. I would then create a new component that includes input fields for the PIN, along with necessary validation to ensure the user enters the correct PIN format. After that, I would implement functionality to confirm the PIN against the previously set value, displaying appropriate messages for success or failure.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will introduce a screen for confirming the user’s PIN during the account creation process, using the provided Figma link as the actual design. This screen will prompt users to re-enter their chosen PIN and check for a match. If the PINs match, they can proceed; if not, an error message will guide them to try again.

I’ll integrate this confirmation screen into the UI flow right after the initial PIN entry and update the backend logic for seamless verification. This enhancement will improve user security and build trust in the application.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
i would like to contribute on this

**Comment by jrmncos** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I'm a Software Enginer SR in web 2.0. Some tickets in this repo are not related exclusive with smart contracts, so my experience can work here. Also I have experience working on mobile. I will apply to various tickets in this repo, so sorry for the spam, I really like the project

### How I plan on tackling this issue
the figma design is clear, I will research how to implemented the PIN logic. Many apps use it

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a cairo dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by Dev-AndresGR** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I don't have experience as a web3 programmer, but I do have the knowledge, because I have been studying it.
As a member of the Coding Dojo, I like to learn and exercise my knowledge, which I think would be an excellent first issue

### How I plan on tackling this issue
The first thing is to enter the Discord or Telegram of the project, request the greatest amount of information available, I look for guides and read the documentation, in order to understand the type of screen they want to add.
I'm a frontend, so adding buttons and so on works very well for me.

**Comment by trbutler4** [comment]
@martinvibes Hey! Please let me know if you have any questions about the issue, You can ask here or send a message in the telegram group here: https://t.me/+8G3EBNnfyS1lNzYx

**Comment by martinvibes** [comment]
hello @trbutler4 please enlighten me more on what i'm supposed to do
