### ISSUE TITLE
[feat] Upgrade account to use Cairo 2.8.4

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#112]
Bring the account contract up to date.

**Comment by akintewe** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I have extensive expertise developing smart contracts and implementing account abstractions using Rust, Cairo, and Kotlin. My knowledge in systems programming with Rust and smart contract development with Cairo puts me well for improving the account contract implementation.


### How I plan on tackling this issue
I would tackle this issue by first reviewing the present account contract structure and identifying places that need to be updated to meet the latest criteria. This includes comparing existing implementations to current best practices for account abstraction, validation mechanisms, and security patterns. I would prioritize implementing any missing functionality and preserving backward compatibility.

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hi, I am a skilled Cairo dev with lots of experience contributing to amazing projects, my profile is a witness to that statement.

### How I plan on tackling this issue
- I will upgrade the contract to 2.8.4, 
- I will also upgrade necessary dependencies without breaking the already existing functionality and tests.
ETA: 2 days

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
i am shantel peters,a frontend and blockchain developer . My background in smart contract development and blockchain technology allows me to identify gaps and efficiently implement modern, secure, and optimized solutions for account contracts.

### How I plan on tackling this issue
To approach the issue of bringing the account contract up to date, I would first review the current contract implementation and compare it with any recent updates or best practices in smart contract development. This would involve checking for security vulnerabilities, compatibility with the latest Solidity versions or blockchain standards (like ERC-4337 for account abstraction), and optimizing gas efficiency. I would then refactor the code to incorporate any new features or improvements needed.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

**Comment by bruhhgnik** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I'm nik, im a core linux dev and i have also worked on ML models and DeFi

### How I plan on tackling this issue
I would want to knnow a bit more details about the issue, then i'll make sure its solved.
eta: 1 day or lesser

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a cairo dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by danielcdz** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello, my name is Daniel Calderon, I'm a software engineer with over 3 years of experience, as a web3 developer I have experience in Starknet and Cairo, I'm part of the Dojo Coding Community and I Have been contributing through OnlyDust a lot recently. I have good experience with unit testing in Cairo, recently I was working on unit testing for Dojo Contracts, on the development of an on chain game.

### How I plan on tackling this issue
In this PR: https://github.com/Scaffold-Stark/speedrunstark/pull/154 , I did a full upgrade of contract and test to the latest version of scarb and snfoundry, I am very familiar with the technologies and I can update your contract and other dependencies such as tests and snfoundry version to the latest ones if you want me to do it! I can finish the work in 2 work days, looking forward to contribute!

**Comment by Gerson2102** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to this project:

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### How I plan on tackling this issue
### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by trbutler4** [comment]
@danielcdz Hey! Please let me know if you have any questions about the issue, You can ask here or send a message in the telegram group here: https://t.me/+8G3EBNnfyS1lNzYx

**Comment by danielcdz** [comment]
@trbutler4 for sure! Thank you for the opportunity!

**Comment by danielcdz** [comment]
@ trbutler4 this is complete! maybe this issue can be closed 🫡
