### ISSUE TITLE
[feat]  test account valid signature 

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#113]
Test is_valid_signature() works as expected (valid returns true, anything else returns false (check 0 hash and empty sigs as well))

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a web3 developer, I have expertise in smart contracts, decentralized technologies, and frameworks like React. I can build innovative dApps, contribute to open-source projects, educate others, and network with industry leaders to advance my career in the decentralized space.

### How I plan on tackling this issue
I will create test cases for the `is_valid_signature()` function to verify it returns `true` for valid signatures and `false` for invalid ones, including tests for a `0` hash, an empty signature, and other malformed inputs. Additionally, test edge cases to ensure robustness. Run all tests to confirm expected behavior.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a frontend and blockchain ,My experience in blockchain development and testing will help me cover a wide range of scenarios to ensure the function behaves correctly in all possible edge cases.

### How I plan on tackling this issue
To solve the issue of testing is_valid_signature(), I would first create a series of test cases where the function is called with valid and invalid signatures. For valid cases, I would generate a correct signature and ensure that the function returns true. For invalid cases, I would test edge scenarios like zero hashes, empty signatures, and incorrect signatures to verify that the function returns false in each case.

**Comment by ooochoche** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a smart contract developer

### How I plan on tackling this issue
I would approach by:

- Testing that a valid signature for a corresponding hash returns `true`

- Testing  that an invalid signature for a given hash returns `false`

- Testing  that passing an empty signature returns `false`

- Testing  that passing a zero hash with a valid signature returns `false`

- Testing  that passing both a zero hash and an empty signature returns `false`

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello I'm a front-end and blockchain developer and I will love to work on this. Kindly assign please

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello I'm a frontend and blockchain developer. I will love to work on this issue. please assign

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a kotlin dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by danielcdz** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello, my name is Daniel Calderon, I'm a software engineer with over 3 years of experience, as a web3 developer I have experience in Starknet and Cairo, I'm part of the Dojo Coding Community and I Have been contributing through OnlyDust a lot recently. I have good experience with unit testing in Cairo, recently I was working on unit testing for Dojo Contracts, on the development of an on chain game.

### How I plan on tackling this issue
To solve this issue I will use the most I can from `snforge_std` package and use the most cheat codes and tools starknet foundry provides for testing to implement the unit tests in the best way, also if you guys want I can help with upgrading the version of this package to a must recent want and refactor all the tests and contracts involved to left all running and working as expected, in the las ODHack I did this for other project take a look into this: , looking forward to contributing to your project!

**Comment by Gerson2102** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to this project and Cairo projects like:

- `Raito`
- `kakarot-ssj`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### How I plan on tackling this issue
### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by trbutler4** [comment]
@Gerson2102 assigned!
