### ISSUE TITLE
[feat] Test execute

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#114]
Test __execute__() works as expected (solo and multi-calls should work as expected)

Might need to create a mock erc20 contract to test calls (see if the wallet is able to do a multi call (try sending eth to 2 accounts from the deployed wallet, both accounts' balance should update)

#### References

All the smart contracts are in the snphone_contracts directory, tests are run with snforge test

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hi, I am a skilled Cairo dev with lots of experience contributing to amazing projects, my profile is a witness to that statement.

### How I plan on tackling this issue
I'll go through the repo to better understand the required functionality.
I'll write a robust test to ensure all edge cases are covered and ensure the right balance are updated

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
i am a frontend and blockchain developer .My experience in smart contract testing and blockchain development enables me to write robust tests for complex scenarios, ensuring that the multi-call functionality works as intended.

### How I plan on tackling this issue
To approach the issue of testing `execute()` for solo and multi-calls, I would first create a mock ERC-20 contract to simulate the necessary transactions. Then, I would deploy a wallet smart contract and write test cases to check the functionality of solo and multi-calls. For multi-calls, I would execute a transaction sending ETH to two accounts simultaneously and ensure that both account balances update correctly.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello I'm a frontend and blockchain developer and I will love to work on this

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
i would read the instructions careully and implement it and also make sure the tests are passing

please kindly assign :)

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello I'm a frontend and blockchain developer. I will love to work on this issue

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello I'm a frontend and a blockchain developer and I will love to work on this 

### How I plan on tackling this issue
- I will first thoroughly review the execute() function in the contract to understand its logic, inputs, and outputs.
- I will identify the scenarios to be tested, especially focusing on both solo and multi-calls.
- I will create a simplified mock ERC-20 contract in Cairo to facilitate testing multi-calls.
- This mock contract will have basic functionalities like updating balances and emitting events on transfer.
- I will write test cases to ensure that the execute() function works correctly when a single call is made.
- I will then write test cases to ensure that multi-call functionality works as expected, i.e., multiple calls within one execution.
- I will test the transfer of ETH to two different accounts and verify that their balances are updated correctly.
- I will use Cairo’s testing framework to set up and write the test cases. The tests will:
    - Deploy the mock ERC-20 contract.
    - Execute solo and multi-calls using the execute() function.
    - Validate expected events and balance updates for all accounts involved
- I will run the test cases to ensure all scenarios pass without issues.
- Debug and fix any issues encountered during the testing process.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a rust dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by dimka90** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a backend engineer with half a decade years of experience in creating and developing applications and smart contract that solves real life problems.

### How I plan on tackling this issue
i will go through the projects and understand it , then write logic for the wallet to be

**Comment by trbutler4** [comment]
@manlikeHB Hey! Please let me know if you have any questions about the issue, You can ask here or send a message in the telegram group here: https://t.me/+8G3EBNnfyS1lNzYx
