### ISSUE TITLE
[feat] Fetch token images from coingecko 

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#125]
Load token images from coingecko.

**Comment by trbutler4** [comment]
Adding issue for work already completed

**Comment by sajalbnl** [comment]
@trbutler4 can I work on this?

**Comment by ooochoche** [comment]
@trbutler4 Please can I work on this issue?

**Comment by ShantelPeters** [comment]
Hi @trbutler4 if this is still open for contribution please can i be assigned to it ?
