### ISSUE TITLE
[feat] Getting started documentation 

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#17]
- [x] #18
- [x] #19
- [x] #20

**Comment by Iwueseiter** [comment]
Hi @trbutler4 can I work on this when it's opened for contribution?

**Comment by trbutler4** [comment]
> Hi @trbutler4 can I work on this when it's opened for contribution?

This is done now, but if you go through the docs and find anything you want to clarify feel free.

**Comment by Iwueseiter** [comment]
Alright
