### ISSUE TITLE
Wallet UI

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#23]
We just want a barebones UI to start. A section to display balance, and send tokens.

**Comment by jasonarias28** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I have basic knowledge in mobile application development acquired through a university course and self-learning experiences in design. Although my experience is limited, I have a strong interest for development and interface design and this will make go the extra mile.

### How I plan on tackling this issue
I'll start by searching the most popular wallet interfaces and use them as reference for my drafts

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I’ve developed music player and online food delivery apps using MVVM, Retrofit, Room Database, and Jetpack Compose. Additionally, I’ve completed an internship where I integrated APIs and built advanced UIs with Kotlin and Jetpack Compose, showcasing my ability to create scalable, maintainable, and efficient applications.

### How I plan on tackling this issue

Approach to the Problem:

I will start by creating a clean, minimalistic UI using Jetpack Compose. The app will have two main sections: one to display the balance and another to send tokens. Using MVVM architecture, I'll ensure a clear separation of concerns. Retrofit will be used to handle API integration for fetching and sending data. Room Database will store the balance locally for offline access. This approach ensures a scalable, maintainable, and user-friendly application foundation.

**Comment by trbutler4** [comment]
@jasonarias28 Thank you for applying! Lets have you wait until some more structured issues are available. This will require a bit of a lift to get going but once we have the initial UI there should be a lot more improvements to make. 

@sajalbnl Thanks for applying! This issue is not quite ready yet, we still need #26, and we are still working on improving docs/adding example starter apps. Jetpack Compose sounds like a good approach. Right now we just want something simple and clean that we can work off of. This issue is just for the UI however, API integration should be done for #24, and we can forgo storing the balance locally for now. (That will be a good issue down the road). I will reach out once this is ready to be worked on.

In the mean time, both of you please join the telegram, and dont hesitate to reach out with questions or to talk about implementation details.

**Comment by trbutler4** [comment]
@sajalbnl Assigned, this one will be combined with #26

**Comment by trbutler4** [comment]
https://www.figma.com/proto/grCm6Jpi2XsQnbAHHE2oCZ/Starknet-Phone-Wallet-App?node-id=0-1&t=BimtIpUM2zDbC7Xm-1

Figma design here should be good for us to get started
