### ISSUE TITLE
Implement with trusted client (eg alchemy)

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#24]
Before the light client is finished, we can work on the wallet app by simply connecting to an existing rpc. 

We will need to be able to: 
- [x] #33
- [x] #35
- [x] #34

This requires: 
- [x] #36 
- [x] #23

**Comment by Gerson2102** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I'm a junior software developer from the Dojo Coding community with contributions to several OnlyDust projects. Including Madara, Cairo native, kakarot-rpc, and Giza. You can check my OD profile here: https://app.onlydust.com/u/Gerson2102

### How I plan on tackling this issue
I have code in Kotling when I was in college, but not too much honestly. But But nevertheless, I would like to try this issue if it is possible.

**Comment by renzobanegass** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hey! I'm Renzo, a Software Engineer with over 5+ years of experience in the IT industry, I recently started contributing to Web3 as part of Dojo Coding, this would be one of my first contributions to the ecosystem! I have plenty of professional experience in Kotlin and JS frameworks.

### How I plan on tackling this issue
First, I want to know more details about this issue, which trusted clients can be viable to implement apart from alchemy? Is there any preference? Should this be implemented in a Rust backend layer or in Kotlin?

I would handle this issue like this:

** Understand the Requirements: **

- Review the existing implementation and documentation of the Starknet Phone repository.

** Research about trusted clients like Alchemy and their Integration **

** Plan the Integration: **

- Identify the key points where the client's services will be utilized (e.g., querying blockchain data, sending transactions).

** Implement the Integration: **

- Add the necessary SDK or API calls to the project. 
- Ensure that the implementation securely handles the API keys and any sensitive information.

** Testing: **

- Write unit and integration tests to verify that the integration works as expected.

** Documentation: **

- Document the changes made to the codebase.
- Provide clear instructions on how to set up and configure the integration.

** Request feedback **

**Comment by trbutler4** [comment]
@Gerson2102 @renzobanegass Hey guys, thanks for applying! we are not quite ready to start working on this issue yet. First we need #26, and I am working on adding an example android application with rust library integration, as well as expanding on the getting started guide. I will reach out once this is ready to be worked on. 

@renzobanegass to answer your questions, there is no preference on light clients. Beerus does have some constraints however, and alchemy fulfills them. The implementation is really up to you. I assume In general, we should try to keep as much code in kotlin as possible. However, if using rust will increase performance or allow you to leverage existing code, then use it. The goal with this issue is minimum functionality for setting up an account, viewing an account balance, and sending a transaction. 

Please join the telegram for any questions, and dont hesitate to reach out to me if you want to talk about how to approach the issue.

**Comment by trbutler4** [comment]
@renzobanegass if you want to work on #35 add a comment and ill assign it, i broke this issue into 3 parts.
