### ISSUE TITLE
Add skeleton starter app for wallet application to repo

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#26]

**Comment by EmmanuelU** [comment]
Hey I will grab this one.

**Comment by trbutler4** [comment]
> Hey I will grab this one.

Assigned!

**Comment by trbutler4** [comment]
@EmmanuelU I think we should use react native, following something similar to: https://github.com/novasamatech/parity-signer

most starknet code will be in rust, so this will let us easily implement rust with android

**Comment by Rayan9064** [comment]
@trbutler4 I am interested in creating a skeleton loader for the wallet application. It would be great opportunity to start this as my first contribution. Please assign this issue to me. Thank you.

**Comment by trbutler4** [comment]
> @trbutler4 I am interested in creating a skeleton loader for the wallet application. It would be great opportunity to start this as my first contribution. Please assign this issue to me. Thank you.

Thanks for applying! Please join our [telegram](https://t.me/+8G3EBNnfyS1lNzYx) to stay up to date. Im handling this one since it needs to be done quickly to allow for more contributions, but keep your eye on the issues there should be more to do soon!
