### ISSUE TITLE
create an account

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#33]
TODO: 
- [x] #49
- [ ] #50

**Comment by kateberryd** [comment]
Hi @trbutler4, I would love to work on this

**Comment by trbutler4** [comment]
> Hi @trbutler4, I would love to work on this

Do you think you can do both the design and implementation? Basically we will need to add a "create account" flow to the wallet app if the account does not already exist. I can also break this up into two issues (one for design and one for implementation)

**Comment by kateberryd** [comment]
Hi @trbutler4 Yes I can work on the flow., from design to implementation

**Comment by trbutler4** [comment]
> @trbutler4, sure, I can handle both the design and implementation. Please break it down into two issues so I can start with the design first and move on to implementation once the design is approved.

sure thing

**Comment by kateberryd** [comment]
Thank you

**Comment by trbutler4** [comment]
> Thank you

you can add on to the current figma, ill paste a link here

**Comment by kateberryd** [comment]
Alright. I will do that

**Comment by trbutler4** [comment]
https://www.figma.com/design/grCm6Jpi2XsQnbAHHE2oCZ/Starknet-Phone-Wallet-App?node-id=0-1&t=0CBRsFd0RF6a9Wws-1

here is the link to the figma. Please request edit access once you are in it
