### ISSUE TITLE
send tokens

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#34]

**Comment by EjembiEmmanuel** [comment]
@trbutler4 I'd love to work on this

**Comment by trbutler4** [comment]
> @trbutler4 I'd love to work on this

I will assign you. You should see a "TODO(34)" comment in the code. This will involve calling a java class that will be implemented in rust, there is a walkthrough of how that works in [the rust in android guide](/docs/src/getting-started/rust-in-android.md)

**Comment by trbutler4** [comment]
@EjembiEmmanuel Hey, have you made any progress on this? We should be using the startknet jvm library instead of rust.

**Comment by trbutler4** [comment]
Unblocking this issue @EjembiEmmanuel

**Comment by trbutler4** [comment]
This should be added to the StarknetClient. Search for TODO(#24) in the code

**Comment by sajalbnl** [comment]
hey @trbutler4 can i work on this

**Comment by lindsaymoralesb** [comment]
Hi! @trbutler4 can I hop in?
I’m Lindsay, Software Eng based in Costa Rica. 
Experienced in full stack dev, but specialized in frontend. Currently learning about web3 and blockchain. I’be been contributing for the last months, feel free to check my od contributions!

**Comment by trbutler4** [comment]
> hey @trbutler4 can i work on this

cant give u all the issues :)

**Comment by trbutler4** [comment]
> Hi! @trbutler4 can I hop in? I’m Lindsay, Software Eng based in Costa Rica. Experienced in full stack dev, but specialized in frontend. Currently learning about web3 and blockchain. I’be been contributing for the last months, feel free to check my od contributions!

I will assign you. We are using this library: https://github.com/software-mansion/starknet-jvm

there should be an example in their repo for sending tokens

**Comment by lindsaymoralesb** [comment]
Perfect, I'll take a look at that. Thank you!

**Comment by trbutler4** [comment]
> Perfect, I'll take a look at that. Thank you!

hey @lindsaymoralesb how is this issue coming along?

**Comment by lindsaymoralesb** [comment]
hey @trbutler4 sorry, I've been loaded with work and haven't been able to work on this! I may be able to work on it next week, but feel free to unassign if it's a blocker. tx!

**Comment by od-hunter** [comment]
Hi @trbutler4 , can I work on this please I’m ready to work.

**Comment by sajalbnl** [comment]
Hey @trbutler4 i want to work on this

**Comment by od-hunter** [comment]
Hi @trbutler4 , please can I be assigned this?

**Comment by ooochoche** [comment]
@trbutler4  I can take on this issue

**Comment by alfatektecnologia** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I have been using Kotlin to develop mobile apps for more than four years, and I am strongly motivated to take on this challenge.

**Comment by trbutler4** [comment]
closing this issue, it will still need to be done but I want to structure issues differently for ODHack
