### ISSUE TITLE
retrieve account balance

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#35]

**Comment by Oshioke-Salaki** [comment]
Can

**Comment by Oshioke-Salaki** [comment]
Gm can I be assigned this?

**Comment by renzobanegass** [comment]
Hi, I'm interested in solving this issue

**Comment by trbutler4** [comment]
> Hi, I'm interested in solving this issue

Assigned. This is gonna involve a Java class that is implemented in rust (so that we can use the starknet-rs library), how that works is outlined in the [rust in android guide](https://docs.starknetphone.xyz/getting-started/rust-in-android.html)

**Comment by renzobanegass** [comment]
Should I wait for #33 or can I start right away?

**Comment by trbutler4** [comment]
> Should I wait for #33 or can I start right away?

you can get started right away, maybe implement with any hard coded account rather than the one that will be created

**Comment by renzobanegass** [comment]
Hi! I'm sorry but I think I'll unassign myself from this issue, I've been dragging another issue for a while and I'm having a hard time closing it, so I can't really focus on this RN. Sorry!

**Comment by trbutler4** [comment]
> Hi! I'm sorry but I think I'll unassign myself from this issue, I've been dragging another issue for a while and I'm having a hard time closing it, so I can't really focus on this RN. Sorry!

No worries, thank you for communicating that!

**Comment by sajalbnl** [comment]
@trbutler4 i want to work on this issue

**Comment by trbutler4** [comment]
> @trbutler4 i want to work on this issue

assigned!
