### ISSUE TITLE
wallet implementation rust library

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#36]
The wallet application will be an interface written in kotlin/java, and the actual wallet implementation behind the scenes will be done with rust. The rust library can be developed first, and then we will connect the rust code to the kotlin/java UI (this will be a new issue).

**Comment by Gerson2102** [comment]
Hey @trbutler4, can i work on this one? I have contributed to Rust projects before.

**Comment by trbutler4** [comment]
> Hey @trbutler4, can i work on this one? I have contributed to Rust projects before.

Assigned! I created a starter rust project in wallet_app/snphone-wallet for you to use. I think using starknet-rs is the way to go. Let me know if you have any question or want to sync on the implementation.

**Comment by Gerson2102** [comment]
Got it!
Thank you so much!
