### ISSUE TITLE
Light Client app UI

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#37]
We need to add a simple UI for the light client app. It should simply have a on/off toggle, and show status (running, not running)

The light client android app can be found in light_client_app/android

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I’ve developed music player and online food delivery apps using MVVM, Retrofit, Room Database, and Jetpack Compose. Additionally, I’ve completed an internship where I integrated APIs and built advanced UIs with Kotlin and Jetpack Compose, showcasing my ability to create scalable, maintainable, and efficient applications.

**Comment by Jemiiah** [comment]
hello @trbutler4 I would love to work on this issue I'm a web3 frontend developer this is my first time contributing to this repository and have made 25 + contribution to other repository and would love to take the opportunity to work on this one I would be delighted if given the opportunity this is my GitHub profile : https://github.com/Jemiiah

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hey! I'm Lau Chaves, and I would like to contribute to this issue!

I have over 5 years of experience working with JavaScript, React, and TypeScript, ruby... Im also part of Dojo Coding Costa Rica.

My primary role has been as a front-end developer, and I have a keen eye for detail and a strong focus on mobile-first approaches. I ensure the quality of my work through rigorous QA processes. Additionally, I'm proficient in working with design tools like Figma and Zeplin to follow designs meticulously. I have a solid knowledge of CSS, Sass, and styled-components.

Feel free to check my onlydust profile here and github profile: lauchaves!


### How I plan on tackling this issue
Id follow these steps:

- Explore `light_client_app/android` to identify where to add the UI and logic.
- Define UI elements, in this case, the toggle switch for on/off and a status indicator and the text that will show status (running, not running)
- Add an event listener to the toggle switch to start/stop the light client service.
- Update the status indicator based on the client's running state.
- Test the UI to ensure correct functionality.

**Comment by trbutler4** [comment]
@Jemiiah Lets have you wait for a less ambiguous issue, this one will be a bit of a lift to get started, since it will quire making a lot of decisions regarding tooling. 

@lauchaves @sajalbnl I am going to assign @sajalbnl to this issue since he has the most kotlin experience and is already handling the wallet UI. Once the groundwork is in it will be easier to assign more issues that are UI related. @lauchaves would you be up for creating a figma design for @sajalbnl to follow? You can use the design I created for the wallet app as a reference: https://www.figma.com/design/grCm6Jpi2XsQnbAHHE2oCZ/Starknet-Phone-Wallet-App?node-id=0-1&t=BimtIpUM2zDbC7Xm-1

If this works let me know and ill create a new issue for the figma design.

**Comment by lauchaves** [comment]
Hey @trbutler4 no prob! That sounds great! I’d love to help out with the Figma design. I’ll use the wallet app design as a guide, thanks for counting me in!

**Comment by trbutler4** [comment]
@sajalbnl @lauchaves I assigned you both to this issue. @lauchaves is handling the figma design (just paste a link here when complete) and @sajalbnl will implement it

**Comment by sajalbnl** [comment]
@trbutler4 okay, will start my work as soon as I get figma design

**Comment by lauchaves** [comment]
Hey @trbutler4 👋, I’ve put together the UI for the light client app. You can check it out [here](https://www.figma.com/design/HZnrurSz9vJ1jvY49HOgSG/Starknet-Phone-Light-Client-app?node-id=0-1&m=dev&t=3eGCzGVX0ILXIYn5-1). Let me know if you have any feedback or if you’d like it done differently. 😊

**Comment by trbutler4** [comment]
> Hey @trbutler4 👋, I’ve put together the UI for the light client app. You can check it out [here](https://www.figma.com/design/HZnrurSz9vJ1jvY49HOgSG/Starknet-Phone-Light-Client-app?node-id=0-1&m=dev&t=3eGCzGVX0ILXIYn5-1). Let me know if you have any feedback or if you’d like it done differently. 😊

perfect, this is all we need for now. @sajalbnl go ahead and get started.
