### ISSUE TITLE
[feat] Generate Keypair 

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/starknet-phone#43]
Generate a keypair to use for Starknet signatures (secp256r1?) and use as the account signing key.

#### References
- https://developer.android.com/privacy-and-security/keystore
- https://developer.android.com/privacy-and-security/cryptography

**Comment by trbutler4** [comment]
i think we should stay away from r1, because of security concerns. 

Here is how the StarkEx crytpo SDK implements it: https://github.com/starkware-libs/starkware-crypto-utils/blob/dev/src/js/key_derivation.ts

**Comment by maxslimb** [comment]
@trbutler4 can I work on this?

**Comment by trbutler4** [comment]
> i think we should stay away from r1 (prefer k1), because of backdoor security concerns.
> 
> Here is how the StarkEx crytpo SDK implements it: https://github.com/starkware-libs/starkware-crypto-utils/blob/dev/src/js/key_derivation.ts
> 
> getKeyPairFromPath i think is specifically what function would work for us

disregard this

**Comment by trbutler4** [comment]
https://github.com/software-mansion/starknet-jvm/blob/main/lib/kotlin-guide.md#creating-account

follow this guide for creating an account

**Comment by trbutler4** [comment]
this can be used to generate the private key for now: 

https://developer.android.com/reference/java/security/KeyPairGenerator
