### ISSUE TITLE
create account design 

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#49]

**Comment by trbutler4** [comment]
https://www.figma.com/design/grCm6Jpi2XsQnbAHHE2oCZ/Starknet-Phone-Wallet-App?node-id=0-1&t=0CBRsFd0RF6a9Wws-1

here is the link to the figma. Please request edit access once you are in it

**Comment by kateberryd** [comment]
Alright

**Comment by kateberryd** [comment]
Can I be assigned

**Comment by trbutler4** [comment]
@kateberryd you should be able to edit the figma design now
