### ISSUE TITLE
[feat] Import existing private key implementation 

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#57]
Implement a flow for users setting up the wallet app to import an existing private key

#### TODO
- [ ] #58
- [x] #59

**Comment by Gerson2102** [comment]
Hey, can I work on this one?

**Comment by Jemiiah** [comment]
I would love to work on this issue

**Comment by trbutler4** [comment]
@Jemiiah can you take #58 and @Gerson2102 you take #59 ?

**Comment by Jemiiah** [comment]
@trbutler4 yes I would I have commented

**Comment by trbutler4** [comment]
@Jemiiah sorry but i actually am going to close this, i dont think we want to worry about importing accounts yet.
