### ISSUE TITLE
token import design

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#61]

**Comment by lauchaves** [comment]
@trbutler4 May I give u hand on this one ? Already contributed with some designs before 😊

**Comment by lauchaves** [comment]
Hey @trbutler4 👋 let me know if this [design ](https://www.figma.com/design/PK2hWyFvoLBGrprYabHecs/Starknet-Phone-Wallet-App-Tokens?node-id=0-1&m=dev&t=fKK0IrwvOCE2MDIG-1) works for you or if you have any feedback 😊

**Comment by trbutler4** [comment]
> Hey @trbutler4 👋 let me know if this [design ](https://www.figma.com/design/PK2hWyFvoLBGrprYabHecs/Starknet-Phone-Wallet-App-Tokens?node-id=0-1&m=dev&t=fKK0IrwvOCE2MDIG-1) works for you or if you have any feedback 😊 Here's[ the demo ](https://www.figma.com/proto/PK2hWyFvoLBGrprYabHecs/Starknet-Phone-Wallet-App-Tokens?node-id=0-1&t=fKK0IrwvOCE2MDIG-1) as well

Looks great! you can go ahead and move on to implementation. Just worry about android implementation with dummy data, functionality can come after the skeleton UI. Also let me know how long this took you
