### ISSUE TITLE
network swap design

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#64]

**Comment by Gift-Naomi** [comment]
I can do this @trbutler4

**Comment by trbutler4** [comment]
> I can do this @trbutler4

assigned :)

**Comment by trbutler4** [comment]
https://www.figma.com/design/grCm6Jpi2XsQnbAHHE2oCZ/Starknet-Phone-Wallet-App?node-id=0-1&t=OJygQcOYWPV9Ennh-1

figma here @Gift-Naomi

**Comment by Gift-Naomi** [comment]
@trbutler4 Thanks sir

**Comment by ooochoche** [comment]
@trbutler4 I can handle this. I am into Design

**Comment by Gift-Naomi** [comment]
@trbutler4 can you add more description to this issue sir

**Comment by Gift-Naomi** [comment]
@trbutler4 Can i get your telegram handle please?

**Comment by trbutler4** [comment]
@Gift-Naomi join the telegram group here: https://t.me/+8G3EBNnfyS1lNzYx

This is simply creating a design for swapping networks. Simply swap between mainnet and testnet. Create the design on the figma linked above, let me know if you are unable to edit. You can look at how argent wallet implements swapping networks for ideas.

**Comment by Gift-Naomi** [comment]
@trbutler4 I am done sir
You can review it on the figma.

**Comment by Gift-Naomi** [comment]
https://www.figma.com/design/grCm6Jpi2XsQnbAHHE2oCZ/Starknet-Phone-Wallet-App?node-id=182-2&node-type=CANVAS&t=gvyELrH89bbvkyIA-0

**Comment by trbutler4** [comment]
> https://www.figma.com/design/grCm6Jpi2XsQnbAHHE2oCZ/Starknet-Phone-Wallet-App?node-id=182-2&node-type=CANVAS&t=gvyELrH89bbvkyIA-0

I added another screen showing the network swap component overlayed on the current wallet design. Looks great, ty!

**Comment by trbutler4** [comment]
@all-contributors add @Gift-Naomi for design
