### ISSUE TITLE
[feat] Add minimal logging to example rust native library

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#66]
Create a new example called rust_android_logging  based on the current example app 

#### References
[Android rust logging ref](https://source.android.com/docs/setup/build/rust/building-rust-modules/android-rust-patterns)

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I have a solid background in Android development and Rust programming, My experience will ensure a seamless and efficient implementation of the rust_android_logging example.






### How I plan on tackling this issue
I will implement the task with the following steps!

Initialize a new Rust library project and add logging dependencies in Cargo.toml then Implement logging functions in src/lib.rs and export them with #[no_mangle].

Compile for Android:
Use cargo-ndk to cross-compile the Rust code for Android architectures.

Integrate with Android:
Add the compiled Rust library to your Android project’s jniLibs.
Create a JNI wrapper in Java to call the Rust logging functions.

Build and Test:
Compile the Android project and test logging functionality in the app.

**Comment by gadyrcdz** [comment]
Hello @trbutler4! , I was reading about this project and if it is still available I'd like to take it and work on it. Also, I am part of Dojo Coding if this helps me.
Let me now, thank you!

**Comment by trbutler4** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).
> 
> ### My background and how it can be leveraged
> I have a solid background in Android development and Rust programming, My experience will ensure a seamless and efficient implementation of the rust_android_logging example.
> 
> ### How I plan on tackling this issue
> I will implement the task with the following steps!
> 
> Initialize a new Rust library project and add logging dependencies in Cargo.toml then Implement logging functions in src/lib.rs and export them with #[no_mangle].
> 
> Compile for Android: Use cargo-ndk to cross-compile the Rust code for Android architectures.
> 
> Integrate with Android: Add the compiled Rust library to your Android project’s jniLibs. Create a JNI wrapper in Java to call the Rust logging functions.
> 
> Build and Test: Compile the Android project and test logging functionality in the app.

Perfect. This is exactly what needs to be done. Assigned!

**Comment by trbutler4** [comment]
> Hello @trbutler4! , I was reading about this project and if it is still available I'd like to take it and work on it. Also, I am part of Dojo Coding if this helps me. Let me now, thank you!

Im Assinged this one to @ScottyDavies. Please join our [telegram](https://t.me/+8G3EBNnfyS1lNzYx) to join in the discussion :)

**Comment by trbutler4** [comment]
@ScottyDavies any progress on this issue?

**Comment by ScottyDavies** [comment]
Yes, I have had multiple progress and would be done latest Tuesday.

**Comment by akintewe** [comment]
I'm currently working on it, it would be ready before Tuesday , i have created a seperate branch

**Comment by akintewe** [comment]
I've submitted a pull request #91 that addresses this issue. The implementation includes:

 Created a new example called rust_android_logging based on the current example app
Initialized a new Rust library project with logging dependencies in Cargo.toml
 Implemented logging functions in src/lib.rs and exported them with #[no_mangle]
Used cargo-ndk to cross-compile the Rust code for Android architectures
Added the compiled Rust library to the Android project's jniLibs
Created a JNI wrapper in Kotlin to call the Rust logging functions
 Compiled and tested the Android project with the new logging functionality



Please review when you have a chance. Let me know if you need any additional information or changes. Thank you

**Comment by ScottyDavies** [comment]
@trbutler4  you can check it out

**Comment by trbutler4** [comment]
> @trbutler4 you can check it out and accept the pull request

I requested changes on it. Apart from the "target" directories that should be added to ignore list, Seems like there are a lot of unrelated changes?

**Comment by ScottyDavies** [comment]
I am already working on the changes, I would soon be done

**Comment by trbutler4** [comment]
closing, this is not needed
