### ISSUE TITLE
[feat] Add kotlin -> rust bindings for creating an account

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#67]
Basically we will need to create a java class to pass the private key, which will call the rust code to create an account with that private key

**Comment by Gerson2102** [comment]
I would like to try this one.

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I have a strong background in both Java and Rust, which positions me well for tasks involving cross-language integration.

### How I plan on tackling this issue
I will implement the issue with the following steps!

I will create a Rust function to accept a private key and perform account creation.
Use #[no_mangle] and extern "C" to make the function callable from Java then compile the Rust code into a shared library (.so, .dll, or .dylib).

Define a native method in Java to interface with the Rust function.
Load the shared library and call the native method with the private key.

Ensure the shared library is accessible in the Java library path and execute the Java program

**Comment by gadyrcdz** [comment]
Hello @trbutler4! ,If it is still available I'd like to take it and work on it. Also, I am part of Dojo Coding if this helps me.
Thank you!

**Comment by trbutler4** [comment]
> I would like to try this one.

assigned to @Gerson2102. @Gerson2102 the outline @ScottyDavies put down is spot on. LMK if you have any other questions.
