### ISSUE TITLE
3rd Place - Token Tycoon

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/starknet-phone#7]
A Monopoly-like game built on Starknet 🎲🏨

With dice rolls enabled by on-chain VRF, players take turns buying available properties on the board with their cash. 

The production stage involves implementing a live multiplayer game mode.

As 
[@art_peace_sn](https://x.com/art_peace_sn)
 demonstrated, fully on-chain games can be played on Starknet for fractions of a cent, and with session keys, the UX will be even smoother 💅

**Comment by marlonedwards** [comment]
I have onboarded this account (marlonedwards) with OnlyDust. Excited to get started!

**Comment by drspacemn** [comment]
paid
