### ISSUE TITLE
2nd Place - Quasm

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/starknet-phone#8]
🥈2rd Place: Quasm by Zach Cook

Providing L3 and appchain infrastructure, Quasm allows developers to participate in Fractal Scaling. It facilitates easy orchestration and servicing of Katana and Madara appchains.

The production stage includes hosting applications on Quasm appchains and providing state settlement to a user-decided Data Availability layer.

For more information: [https://quasm.io](https://t.co/tLIy24WGnK)

**Comment by web3technologies** [comment]
Hello excited to be selected in second place! My account: web3technologies has been onboarded on Onlydust.

**Comment by drspacemn** [comment]
paid
