### ISSUE TITLE
[feat] Default wallet implementation to env vars

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#80]
#### References

Default wallet should be loaded from local.properties. 

Search TODO(#80) to find variables currently being used

**Comment by sajalbnl** [comment]
Hey. @trbutler4 i want to work on this

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am web3/frontend developer

### How I plan on tackling this issue
Can i work on this?

**Comment by trbutler4** [comment]
> Hey. @trbutler4 i want to work on this

assigning
