### ISSUE TITLE
[feat] Refactor wallet_app/android 

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#81]
Right now, most of the "Activity" files in wallet_app/android are just in the main directory. We should refactor so that all activities are in the ui/activity folder.

**Comment by sajalbnl** [comment]
@trbutler4 i want to work on this

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am web3/frontend developer

### How I plan on tackling this issue
i will Refactor all activities that are in the ui/activity folder

**Comment by trbutler4** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).
> 
> ### My background and how it can be leveraged
> I am web3/frontend developer
> 
> ### How I plan on tackling this issue
> i will Refactor all activities that are in the ui/activity folder

Assiging! ty
