### ISSUE TITLE
[feat] Load correct balance and address based on current wallet in local.properties

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#82]
Update the wallet app to load and display the balance for the current wallet rather than hardcoded.

**Comment by trbutler4** [comment]
Search for "TODO(#82)" in wallet_app/android directory

**Comment by Iwueseiter** [comment]
Hi @trbutler4 can I work on this?

**Comment by sajalbnl** [comment]
@trbutler4 i want to work on this
