### ISSUE TITLE
[feat] Refactor wallet app design 

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#83]
Currently, our account creation flow behaves more like creating an ethereum wallet. Lets drop the backup words, and instead simply generate a private key and create the account. We can provide for exporting the private key for now. This will be temporary until we can implement better account functionality. 
#### References
[Figma](https://www.figma.com/design/grCm6Jpi2XsQnbAHHE2oCZ/Starknet-Phone-Wallet-App?node-id=83-2&node-type=canvas&t=BBhS5LyAykIInhKP-0)

**Comment by ooochoche** [comment]
I

**Comment by ShantelPeters** [comment]
Hi @trbutler4 can I please be assigned to this issue ?

**Comment by trbutler4** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).
> 
> ### My background and how it can be leveraged
> @trbutler4 I can work on this
> 
> ### How I plan on tackling this issue
> I am a ui/ux designer, I've gone through the previous design and know exactly what you want to be done

Assigned! If you need figma permissions let me know.

**Comment by trbutler4** [comment]
@all-contributors add @ooochoche for design
