### ISSUE TITLE
[feat] Explore account implementation options

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#84]
Explore some different options for handling the accounts for the wallet app. The general focus/priority should be ease of use, anonymity, and a simple offline backup feature (eg. uploading a private key).

**Comment by mubarak23** [comment]
@trbutler4 kindly assigned

**Comment by trbutler4** [comment]
@mubarak23 how is this going? do you have a write up or something i can look at?

**Comment by mubarak23** [comment]
> @mubarak23 how is this going? do you have a write up or something i can look at?

Yes, I will create a draft PR

**Comment by trbutler4** [comment]
> > @mubarak23 how is this going? do you have a write up or something i can look at?
> 
> Yes, I will create a draft PR

awesome thank you
