### ISSUE TITLE
[feat] Implement CoinGecko api to get token prices

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#86]
Add support to the wallet app (wallet_app/android) for coingecko API to retrieve token price. The free (demo) plan is enough for now. 

#### References

https://docs.coingecko.com/v3.0.1/reference/introduction

**Comment by Gerson2102** [comment]
Hey can I work on it? Is related to Kotlin?

**Comment by sajalbnl** [comment]
Hey @trbutler4 i want to work on this

**Comment by Iwueseiter** [comment]
Hi @trbutler4 please can I work on this?

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Mobile Software Developer utilising Dart, Swift and Kotlin.

### How I plan on tackling this issue
Implement API service interface and instances.
Create data models.

**Comment by coxmars** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hi @trbutler4, I'm a software developer with 2+ years of experience with Java, C#, Dart and others technologies and I'm member of Dojo Coding community here in CR. I would like to contribute to this project for my first time.

### How I plan on tackling this issue
I’d approach this by using my experience working with different APIs from other services. I’d integrate the CoinGecko API to fetch token prices by creating a service or utility class to handle the API requests and responses.

**Comment by trbutler4** [comment]
I am assigning @sajalbnl since he is already familiar with this code

**Comment by trbutler4** [comment]
done
