### ISSUE TITLE
[feat] Add a way to save and access token information in the wallet app

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#87]
We want to store a list of token data (address, name, path to logo) for the wallet app to read from, so that it know what tokens to fetch the users balance for. We also want to support users adding arbitrary tokens, which will persist with the app.

**Comment by Jemiiah** [comment]
@trbutler4 can I work on this ?

**Comment by ShantelPeters** [comment]
Hi @trbutler4 can I please be assigned to this issue?

**Comment by sajalbnl** [comment]
Hey @trbutler4 can i work on this. I am familiar with the flow

**Comment by Iwueseiter** [comment]
Hi @trbutler4 please can I work on this?

**Comment by Osatuyi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I can do this

### How I plan on tackling this issue
Can I be assigned this

**Comment by trbutler4** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).
> 
> ### My background and how it can be leveraged
> Hi @trbutler4 can I please be assigned to this issue?
> 
> ### How I plan on tackling this issue
> I will approach the problem with the following:
> 
> 1. Use DataStore
> 2. Define Token Data Class
> 3. Create DataStore
> 4. Store tokens
> 5. Fetch Tokens
> 6. Add Arbitrary Tokens
> 7. Fetch User Balances

Assigning! thank you for outlining your approach.

**Comment by trbutler4** [comment]
> Thank you sir @trbutler4 I will start working on it immediately .

How is this going? Have you made any progress? Do you have any questions? If not i want to unblock this issue for ODHack

**Comment by ShantelPeters** [comment]
> > Thank you sir @trbutler4 I will start working on it immediately .
> 
> How is this going? Have you made any progress? Do you have any questions? If not i want to unblock this issue for ODHack

Hi @trbutler4 i am on it and I will create a PR soon 
I will definitely meet you if there are questions 
Thank you sir …

**Comment by trbutler4** [comment]
> > > Thank you sir @trbutler4 I will start working on it immediately .
> > 
> > 
> > How is this going? Have you made any progress? Do you have any questions? If not i want to unblock this issue for ODHack
> 
> Hi @trbutler4 i am on it and I will create a PR soon I will definitely meet you if there are questions Thank you sir …

great thank you

**Comment by trbutler4** [comment]
@ShantelPeters any updates? not trying to rush you but i want this issue either done or unblocked for ODHack on the 24th

**Comment by trbutler4** [comment]
unblocking this

**Comment by ooochoche** [comment]
@trbutler4 can I work on this
