### ISSUE TITLE
[feat] Implement new account creation/import flow 

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#88]
Implement the new flow as prototyped on figma 

#### References

https://www.figma.com/design/grCm6Jpi2XsQnbAHHE2oCZ/Starknet-Phone-Wallet-App?node-id=83-2&node-type=canvas&t=8XrStFW4SOQCnBHu-0

**Comment by trbutler4** [comment]
@kateberryd assigning you

**Comment by kateberryd** [comment]
@trbutler4 I would love to work on this. Please assign

**Comment by ScottyDavies** [comment]
@trbutler4 can i hop on this?

**Comment by ScottyDavies** [comment]
Still awaiting response
